# Generated by Django 4.0.3 on 2022-05-05 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='modified_at',
            field=models.DateField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200, verbose_name='이메일')),
                ('phone', models.CharField(max_length=11, verbose_name='전화번호')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='질문작성자', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coment', models.TextField(verbose_name='답변내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='운영자', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
