# Generated by Django 4.0.3 on 2022-05-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_services', '0002_alter_faq_modified_at_inquiry_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
    ]
