# Generated by Django 4.0.3 on 2022-05-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_services', '0003_alter_faq_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='category',
            field=models.CharField(choices=[('NO', 'NO'), ('AC', 'AC'), ('MISC', 'MISC')], default='NO', max_length=4),
        ),
    ]
